spring:
  ai:
    mcp:
      server:
        name: best-image-search-mcp-server
        version: 0.0.1
        type: SYNC
        stdio: false


search_api:
  api-key: bIZKneVIzqLoE5lmb7pJzmHYcDTJibCo7I0G1t8H2DYJSE1P30GXl3Go